add_requires('gtest', 'nlohmann_json')
add_rules("mode.debug")

target("ConcertoCore")
    set_kind("shared")
    set_symbols("debug")
    set_warnings("everything")
    set_languages("cxx20")
    add_packages('nlohmann_json')
    add_includedirs('Include', 'Include/Math')
    add_files('Src/*.cpp', 'Src/Math/*.cpp')

target("ConcertoCoreTests")
    set_kind("binary")
    set_symbols("debug")
    set_warnings("everything")
    set_languages("cxx20")
    add_files('Tests/*.cpp')
    add_packages('gtest')
    add_packages('nlohmann_json')
    add_includedirs('Include', 'Include/Math')
    add_files('Src/*.cpp', 'Src/Math/*.cpp')
